### ISSUE TITLE
What fonts are used?

### ISSUE THREAD

**Issue by slopslug** [marmmaz/FirefoxCSS#1]
I know, the theme isn't built for windows but tought I'd give it a try anyway. Without any changes it looks like this 
![image](https://user-images.githubusercontent.com/47635446/103468436-3ca7f380-4d59-11eb-99c3-37478ced0554.png)

May i know the names of the fonts used so that i might be able to fix this issue?

**Comment by marmmaz** [comment]
Nice to see you try it! The font is Andale Mono.

**Comment by slopslug** [comment]
Thanks for the reply, will try!
