### ISSUE TITLE
Not all styles working

### ISSUE THREAD

**Issue by guidoferreyra** [marmmaz/FirefoxCSS#2]
Hi, I installed the theme but It doesn’t fully work for me
If you see in the screepcapture the background of the tab bar is white and all the context menu too.
Any ideas on how I can solve this?

![Captura de Pantalla 2021-01-21 a la(s) 11 42 09](https://user-images.githubusercontent.com/1755590/105366588-48f7d180-5bde-11eb-8a5a-1b29f1697e6b.png)

Also how can I keep the tab bar always visible?

Thanks!

**Comment by marmmaz** [comment]
Hey, 

For the colors you need to first install **Firefox Color**, it's a free Firefox add-on: https://addons.mozilla.org/en-US/firefox/addon/firefox-color/

After installing the add-on apply my theme, here is a link: https://color.firefox.com/?theme=XQAAAAJUAQAAAAAAAABBKYhm849SCia48_6EGccwS-xMDPr7thdH6_4ErpiIjBgjl6kvKSCXjM5WXDG4Cjy1EaSGG1_TR3iUDV6o9yCCamOh-s-hlIs5DzTo4WqkXScLht-NnmR2ESD4uJhqPW6frhgUtvDqF5111kzunGAQXxigm1NzhmAUopQk0LLBqF6rDub18hpf8rJ4gApxwi195CODHG1EoL4jYH7mz9vXTjtR0xCh87HgJ9Y6K7G-n_-K9gAA

As for the tab bar, go to the userChrome.css file and delete rows 1-85.

Cheers!

**Comment by guidoferreyra** [comment]
Thanks a lot, now it works perfect. Probably you could add this to the Readme :)
